### ISSUE TITLE
IKEA on of button not working since 2.2.0

### ISSUE THREAD

**Issue by tutasca** [madchicken/homebridge-zigbee-nt#154]
Since update to 2.2.0 when pressing on or off sends double signals as on and off

**Comment by kittapasp** [comment]
I've a same problem too on 2.2.4 with IKEA Trådfri ON/OFF Switch (model E1743).

**Comment by Figo66** [comment]
I am using version 2.2.4 installed on homebridge on a raspberry pi using raspbian. I have the same problem like exposed above. When pressing any button all button actions trigger. Thi happens with ikea on/off switch and the other remote that i have(TRADFRI remote control, IKEA E1524/E1810). for the IKEA E1524/E1810 when you press either buttons all 5 buttons trigger.

**Comment by madchicken** [comment]
Should be fixed now

**Comment by Figo66** [comment]
Hello,
Updated to latest version and the issue has changed, but still an issue, now for a 2 button remote, when pressing button 1 (short or long press) it sends button 2, than button 1 events. When pressing button 2 it does only button 2

Thanks,
Alexandru Tudor

**Comment by Figo66** [comment]
Also tested the 5 button remote from ikea, on test all buttons are sending button 5 events but from all the 5 buttons just 4 of them are working(the middle on/off button does not send an event  )

**Comment by huddx01** [comment]
Same here on v2.5.1 on a 5 Button Ikea Remote... The Power Button doesnt work...
And the other 4 Buttons seem all to send the same Signal to the same Actor... Regardless if i configure Brightness to Actor1 and Left/Right to Actor2...

**Comment by madchicken** [comment]
Sorry for this annoying bug, I'll try to get it fixed in the next few days

**Comment by madchicken** [comment]
@Figo66 @huddx01 @tutasca @kittapasp Can someone test version 2.5.2-beta.1 and tell me if buttons are now working as expected?

**Comment by madchicken** [comment]
I forgot to ask: which device are you testing? Ikea On/Off or something else?

**Comment by huddx01** [comment]
> I forgot to ask: which device are you testing? Ikea On/Off or something else?

Its an IKEA Remote... as in my logs above...

```
 _manufacturerName: 'IKEA of Sweden',
    _powerSource: 'Battery',
    _modelID: 'TRADFRI remote control',
    _applicationVersion: 33,
    _stackVersion: 98,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20190708',
    _softwareBuildID: '2.3.014',
```

**Comment by madchicken** [comment]
@huddx01 could you please attach the homebridge log after a restart? I need to understand which device is actually recognised from the plugin. And sorry for my delay in responding, but I am out for work and it's a bit difficult for me to follow "personal projects" in this period

**Comment by madchicken** [comment]
@huddx01 I got on remote from IKEA and I finally found the problem...it's fixed in beta.6 version
