### ISSUE TITLE
IKEA motion sensor?

### ISSUE THREAD

**Issue by vascott1** [madchicken/homebridge-zigbee-nt#18]
Hi there. Got this up and running and when I put the motion sensor in "pairing" mode it shows up. All the info is there but it says it is unrecognized. It says this every minute. I turned off the ability to allow new things to be discovered and the errors went away. Is the motions sensor supported? Is there something I need to add to the config? 

Thanks!

**Comment by madchicken** [comment]
Just to be sure, are we talking about this? https://www.zigbee2mqtt.io/devices/E1525_E1745.html

**Comment by vascott1** [comment]
Yes. That is the device I have.
  

  
  

  
  
>

**Comment by madchicken** [comment]
I added it to the next release. If you want I can publish it as unstable, so you can try it now.

**Comment by vascott1** [comment]
That would be great :) can you tell
  
Me how I would install the unstable
  
Release?   
  

  
Thanks very much!
  

  
  

  
  
>

**Comment by madchicken** [comment]
You should do it by doing something like:
```
sudo npm I -g homebridge-zigbee-nt@unstable
```

**Comment by vascott1** [comment]
Tried unstable. No luck installing Guess I will wait for the next release

pi@homebridge:/dev $ sudo -E -n npm install homebridge-zigbee-nt@unstable

> @serialport/bindings@8.0.8 install /dev/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.0 runtime=node arch=arm libc= platform=linux)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/dev/node_modules/@serialport/bindings/build'
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /dev/node_modules/@serialport/bindings
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/dev/package.json'
npm WARN dev No description
npm WARN dev No repository field.
npm WARN dev No README data
npm WARN dev No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/zigbee-herdsman/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/zigbee-herdsman/node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@8.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-08-10T22_03_11_710Z-debug.log

**Comment by madchicken** [comment]
I released version 1.0.0, you can try it out. It also add a backup radio channel to improve reliability of the dongle (sorry, this is an issue with the HW, not the plugin).
I am gonna close this. Feel free to reopen a new one if the added device doesn't work

**Comment by vascott1** [comment]
Thanks. Will test it this evening. Really appreciate the hard work. Hopefully I will start seeing devices being added. Still not sure why that stopped!
  

  
  

  
  
>
