### ISSUE TITLE
Error “Reading State"

### ISSUE THREAD

**Issue by EdwardChamberlain** [madchicken/homebridge-zigbee-nt#32]
Hi, there seems to be a error that causes the entire module to stop responding. Log shows repeated copies of this message: 

```
Reading 'state' to '0x000d6ffffeff6164' failed: 'Error: Read 0x000d6ffffeff6164/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Cannot request when znp has not been initialized yet)’
```

**Comment by EdwardChamberlain** [comment]
Also in the log is repeated:
```
Rejecting unresolved promise after 7255ms ("0x086bd7fffe519524|1”)
```

**Comment by EdwardChamberlain** [comment]
This seems to be a repeated issue requiring a restart of the server (raspberry pi), restarting the service is not working.

**Comment by madchicken** [comment]
Can you tell me which dongle are you using (and firmware)? Also, which device did you pair?

**Comment by EdwardChamberlain** [comment]
Sure:
Dongle: CC2531
Firmware: CC2531ZNP-2018090201.hex (as specified [here](https://github.com/itsmepetrov/homebridge-zigbee/blob/master/docs/Flashing.md))
And I paired an [Ikea socket](https://www.ikea.com/gb/en/p/tradfri-control-outlet-kit-10364797/)

The socket works (I have about 8 paired) and is functional ~80% of the time. This error shows up about 2/3 times a week and requires a hard reboot of the server.

**Comment by madchicken** [comment]
Uhm, I think that one is a bit outdated, can you try reflashing with this?

 https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2531

**Comment by EdwardChamberlain** [comment]
I will give updating the stick firmware a go. (hopefully I wont have to re-pair everything!)

I think I have managed to make the error slightly more reproducible. I have a scene set in apple home (called “night”) that turns everything in the house off but it also turns off “allow Zigbee join” and “Zigbee Touchlink”. It seems to be that when I run this scene the plug-in dies! 

I was able to catch the log right as it happened:

```[10/10/2020, 23:49:38] [ZigBee] Zigbee: disabling joining new devices.
[10/10/2020, 23:49:38] [ZigBee] Starting touchlink factory reset...
[10/10/2020, 23:49:47] [ZigBee] Writing 'state' to '0x000d6ffffeff6164' failed: 'Error: Command 0x000d6ffffeff6164/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (AREQ - AF - dataConfirm after 9000ms)'
[10/10/2020, 23:49:47] [ZigBee] Writing 'state' to '0x086bd7fffe519524' failed: 'Error: Command 0x086bd7fffe519524/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (AREQ - AF - dataConfirm after 9000ms)’```

**Comment by madchicken** [comment]
Ah! Tochlink should not be "touched" until you really want to factory reset some device, because it changes the status of the dongle and set it to a different mode. I would suggest to move out from the scene the two virtual buttons

**Comment by manuchis** [comment]
Hi! I'm confused here... I'm having a lot of troubles and I thought that reflashing the dongle would solve it. I saw your suggestion @madchicken about the new version, however you point to a "router" version and not  to a "coordinator". And coordinator in that repository is the old one. I flashed with the router version and it is not recognized now, so I will go back to the previous version. Can you clarify this for me?

**Comment by manuchis** [comment]
Hi! I still running with problems. After one or two days the raspberry start receiving errors from the Zigbee. The only way to recover is to unplug the raspberry (no command makes it work, even reboot). 

Node version 12.19
Plugin version 1.0.5
UI version 4.31.0

Log: 
```
[11/4/2020, 18:26:32] [ZigBee Hub] Cannot configure device TRADFRI ON/OFF switch: Bind 0x14b457fffec8d738/1 genOnOff from '901' failed (SREQ '--> ZDO - bindReq - {"dstaddr":50395,"srcaddr":"0x14b457fffec8d738","srcendpoint":1,"clusterid":6,"dstaddrmode":1,"dstaddress":"0x0000000000000385","dstendpoint":255}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))
[11/4/2020, 18:26:43] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:27:12] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:27:18] [ZigBee Hub] New state for 0xec1bbdfffea92099 { state: 'ON', brightness: 125 }
[11/4/2020, 18:27:36] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:27:42] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:28:01] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:28:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:28:11] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'ON' }
[11/4/2020, 18:28:22] [ZigBee Hub] Writing 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no resources' (26))'
[11/4/2020, 18:28:30] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:28:49] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:28:55] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
Rejecting unresolved promise after 8651ms ("0x00124b001f79d7f0|11")
Rejecting unresolved promise after 8646ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:29:14] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:29:20] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:29:38] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:29:43] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255 }
[11/4/2020, 18:29:46] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:29:46] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'ON', brightness: 255 }
[11/4/2020, 18:29:56] [ZigBee Hub] Writing 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no resources' (26))'
Rejecting unresolved promise after 9287ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:30:08] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
Rejecting unresolved promise after 9918ms ("0x00124b001f79d7f0|11")
Rejecting unresolved promise after 9900ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:30:21] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:30:33] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:30:46] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
Rejecting unresolved promise after 8095ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:30:58] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:03] [ZigBee Hub] Can't find message in queue for key 0xec1bbdfffea92099|1 [
  {
    timestamp: 1604511058582,
    message: '0x00124b001f79d7f0|11',
    promise: DeferredPromise {
      resolve: [Function],
      reject: [Function],
      promise: [Promise]
    }
  },
  {
    timestamp: 1604511058587,
    message: '0x00124b001f79d7f0|11',
    promise: DeferredPromise {
      resolve: [Function],
      reject: [Function],
      promise: [Promise]
    }
  }
]
[11/4/2020, 18:31:03] [ZigBee Hub] Device state (GL-C-009):  {}
[11/4/2020, 18:31:07] [ZigBee Hub] Device state (GL-C-009):  { state: 'ON' }
[11/4/2020, 18:31:07] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:31] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:31] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:56] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:31:56] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'ON', brightness: 255, brightness_percent: NaN }
Rejecting unresolved promise after 6125ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:32:04] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:06] [ZigBee Hub] Writing 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no resources' (26))'
[11/4/2020, 18:32:29] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:37] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":61,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,241,0,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:32:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] Writing 'state' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":63,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,243,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:32:54] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:32:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:32:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:02] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:18] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] Writing 'state' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":87,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,253,1]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:33:23] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'ON', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:33:23] [ZigBee Hub] Writing 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":8,"transid":88,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,254,4,254,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:33] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'Timeout' (9999))'
[11/4/2020, 18:33:33] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:33:47] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:33:57] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:34:13] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:34:21] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:34:42] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:34:46] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:35:07] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
Rejecting unresolved promise after 6761ms ("0x00124b001f79d7f0|11")
Rejecting unresolved promise after 6754ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:35:10] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:35:31] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:35:33] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:35:58] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:36:08] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
Rejecting unresolved promise after 5554ms ("0x00124b001f79d7f0|11")
[11/4/2020, 18:36:23] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:36:24] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:36:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:36:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:13] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:14] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:37] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:39] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:39] [ZigBee Hub] Reading 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genLevelCtrl(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":8,"transid":229,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,35,0,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:37:39] [ZigBee Hub] Writing 'state' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":230,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,36,1]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:37:39] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'ON', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:37:39] [ZigBee Hub] Writing 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":8,"transid":231,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,37,4,254,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:37:40] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:40] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:40] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:37:40] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:40] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:37:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:03] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:06] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:38:19] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:30] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":27,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,58,0,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:38:44] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":28,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,59,0,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:38:44] [ZigBee Hub] Reading 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genLevelCtrl(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":8,"transid":29,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,60,0,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:38:44] [ZigBee Hub] Writing 'state' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":30,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,61,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:38:44] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:44] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:38:58] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":47,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,70,0,0,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:39:00] [ZigBee Hub] Writing 'state' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SREQ '--> AF - dataRequest - {"dstaddr":18121,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":48,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,71,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
[11/4/2020, 18:39:00] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:24] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:24] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:38] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:49] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:52] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:39:59] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:40:17] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:40:24] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:40:42] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:40:49] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:41:03] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:41:03] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:41:03] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:41:17] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:41:28] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:41:31] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'ON', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:41:41] [ZigBee Hub] Writing 'brightness' to '0x00124b001f79d7f0' failed: 'Error: Command 0x00124b001f79d7f0/11 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no resources' (26))'
[11/4/2020, 18:41:42] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:42:04] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:42:05] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:42:34] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:42:51] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:42:59] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:42:59] [ZigBee Hub] New state for 0x00124b001f79d7f0 { state: 'OFF', brightness: 255, brightness_percent: NaN }
[11/4/2020, 18:43:16] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:43:24] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:43:40] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:43:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:05] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:19] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:30] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:32] [Broadlink RM] Projector getSwitchState: false
Rejecting unresolved promise after 6857ms ("0xec1bbdfffe9ea5ff|1")
Rejecting unresolved promise after 6853ms ("0xec1bbdfffe9ea5ff|1")
Rejecting unresolved promise after 6844ms ("0xec1bbdfffe9cdbbd|1")
Rejecting unresolved promise after 6840ms ("0xec1bbdfffe9cdbbd|1")
Rejecting unresolved promise after 6823ms ("0xec1bbdfffe1b8410|1")
Rejecting unresolved promise after 6818ms ("0xec1bbdfffe1b8410|1")
Rejecting unresolved promise after 6814ms ("0xec1bbdfffe1c9011|1")
Rejecting unresolved promise after 6810ms ("0xec1bbdfffe1c9011|1")
Rejecting unresolved promise after 6806ms ("0xec1bbdfffe1cab14|1")
Rejecting unresolved promise after 6801ms ("0xec1bbdfffe1cab14|1")
Rejecting unresolved promise after 6798ms ("0xec1bbdfffe951e3f|1")
Rejecting unresolved promise after 6794ms ("0xec1bbdfffe951e3f|1")
[11/4/2020, 18:44:43] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:44:48] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:12] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:12] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:45:35] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:46:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:46:00] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:46:15] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:46:24] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:46:39] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:46:40] [Broadlink RM] Projector getSwitchState: false
Rejecting unresolved promise after 8165ms ("0xec1bbdfffe1cab14|1")
Rejecting unresolved promise after 8161ms ("0xec1bbdfffe1cab14|1")
Rejecting unresolved promise after 8152ms ("0xec1bbdfffe9cdbbd|1")
Rejecting unresolved promise after 8148ms ("0xec1bbdfffe9cdbbd|1")
Rejecting unresolved promise after 8144ms ("0xec1bbdfffe1b8410|1")
Rejecting unresolved promise after 8140ms ("0xec1bbdfffe1b8410|1")
Rejecting unresolved promise after 8136ms ("0xec1bbdfffe1c9011|1")
Rejecting unresolved promise after 8132ms ("0xec1bbdfffe1c9011|1")
Rejecting unresolved promise after 8128ms ("0xec1bbdfffe9ea5ff|1")
Rejecting unresolved promise after 8109ms ("0xec1bbdfffe9ea5ff|1")
Rejecting unresolved promise after 8105ms ("0xec1bbdfffe951e3f|1")
Rejecting unresolved promise after 8101ms ("0xec1bbdfffe951e3f|1")
[11/4/2020, 18:46:56] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:03] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:21] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:29] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:46] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:47:54] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:48:01] [ZigBee Hub] No response from Zigbee LED controller dimmer. Is it online?
[11/4/2020, 18:48:19] [ZigBee Hub] No response from TRADFRI LED bulb GU10 400 lumen, dimmable. Is it online?
[11/4/2020, 18:48:31] [ZigBee Hub] Reading 'state' to '0xec1bbdfffe9ea5ff' failed: 'Error: Read 0xec1bbdfffe9ea5ff/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:48:44] [ZigBee Hub] Reading 'state' to '0xec1bbdfffe9cdbbd' failed: 'Error: Read 0xec1bbdfffe9cdbbd/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:48:55] [ZigBee Hub] Reading 'brightness' to '0xec1bbdfffe9ea5ff' failed: 'Error: Read 0xec1bbdfffe9ea5ff/1 genLevelCtrl(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:49:09] [ZigBee Hub] Reading 'brightness' to '0xec1bbdfffe9cdbbd' failed: 'Error: Read 0xec1bbdfffe9cdbbd/1 genLevelCtrl(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:49:21] [ZigBee Hub] Reading 'state' to '0xec1bbdfffe1b8410' failed: 'Error: Read 0xec1bbdfffe1b8410/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:49:24] [Broadlink RM] Projector getSwitchState: false
Rejecting unresolved promise after 9626ms ("0xec1bbdfffe1cab14|1")
Rejecting unresolved promise after 9622ms ("0xec1bbdfffe1cab14|1")
Rejecting unresolved promise after 9614ms ("0xec1bbdfffe9cdbbd|1")
Rejecting unresolved promise after 9610ms ("0xec1bbdfffe9cdbbd|1")
Rejecting unresolved promise after 9606ms ("0xec1bbdfffe1b8410|1")
Rejecting unresolved promise after 9603ms ("0xec1bbdfffe1b8410|1")
Rejecting unresolved promise after 9598ms ("0xec1bbdfffe1c9011|1")
Rejecting unresolved promise after 9594ms ("0xec1bbdfffe1c9011|1")
Rejecting unresolved promise after 9589ms ("0xec1bbdfffe9ea5ff|1")
Rejecting unresolved promise after 9585ms ("0xec1bbdfffe9ea5ff|1")
Rejecting unresolved promise after 9566ms ("0xec1bbdfffe951e3f|1")
Rejecting unresolved promise after 9562ms ("0xec1bbdfffe951e3f|1")
[11/4/2020, 18:49:34] [ZigBee Hub] Reading 'state' to '0xec1bbdfffe1c9011' failed: 'Error: Read 0xec1bbdfffe1c9011/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:49:45] [ZigBee Hub] Reading 'brightness' to '0xec1bbdfffe1b8410' failed: 'Error: Read 0xec1bbdfffe1b8410/1 genLevelCtrl(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
[11/4/2020, 18:49:59] [ZigBee Hub] Reading 'brightness' to '
```

**Comment by manuchis** [comment]
Ok, same problem appeared in the Zigbee2Mqtt and it was solved in 1.15.0 version. I'm trying to figure out what is the reason and how to solve it.

https://github.com/Koenkk/zigbee2mqtt/issues/4307

**Comment by madchicken** [comment]
It seems there is a firmware that is more stable now (source routing). We should definitely try it. I will updated dependencies in the meanwhile

**Comment by manuchis** [comment]
I’ve already tested changing the router fw but does not solves the problem, also in the z2m thread they tested with original fw.
The problem was solved in the z2m code but I cannot figure out how.

Manuel Portela, PhD
Cel Es. +34 600 851 104
Follow me: @Portela_Man
manuchis.net

**Comment by EdwardChamberlain** [comment]
I can confirm that I am still having this issue every 2/3 days. Still not 100% sure what is causing it but avoiding the touchlink buttons doesn't seem to have resolved it. Further error messages: 

```
[11/11/2020, 16:26:10] [ZigBee] Reading 'state' to '0x680ae2fffe7d5012' failed: 'Error: Read 0x680ae2fffe7d5012/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SRSP - AF - dataRequest after 6000ms)'
```

It seems that zigbee2MQTT doesn't face this issue but I would like to continue using this plugin due to the ease of adding devices.

**Comment by manuchis** [comment]
> I can confirm that I am still having this issue every 2/3 days. Still not 100% sure what is causing it but avoiding the touchlink buttons doesn't seem to have resolved it. I can confirm that rebooting the server reoslves the issue but restarting homebridge does not. Perhaps power cycling the dongle is what is required? Further error messages:
> 
> ```
> [11/11/2020, 16:26:10] [ZigBee] Reading 'state' to '0x680ae2fffe7d5012' failed: 'Error: Read 0x680ae2fffe7d5012/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SRSP - AF - dataRequest after 6000ms)'
> ```
> 
> It seems that zigbee2MQTT doesn't face this issue but I would like to continue using this plugin due to the ease of adding devices. Unfortunately, I don't think I am able to offer any technical support with this one!

I have my zigbee devices turned off for a week now... 
My last errors were:
```
[11/12/2020, 14:00:44] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
```
It's looks like that I have to map everything again, but I don't know at this point if it would work to take the time to do it.
I'm also thinking on changing strategies because keep this plugin running is a lot of effort. I found "homebridge-z2m" plugin that would directly connect it to z2m but I don't know yet how stable is it.

**Comment by madchicken** [comment]
I'll take a look at this later today. I am having a lot of trouble upgrading and maintaining this plugin for lack of time 😞

**Comment by madchicken** [comment]
Can some of you test the branch `v1.0.6`? It is just an update of dependencies...

**Comment by manuchis** [comment]
Hi @madchicken thanks for your effort. I  would like to help but I'm not enough expert here. 

v1.0.6 its failinng to compile
```
yarn run v1.22.5
warning homebridge-zigbee-nt@1.0.6: The engine "homebridge" appears to be invalid.
$ yarn clean && yarn build-ts
warning homebridge-zigbee-nt@1.0.6: The engine "homebridge" appears to be invalid.
$ rimraf dist/
warning homebridge-zigbee-nt@1.0.6: The engine "homebridge" appears to be invalid.
$ tsc
src/zigbee/zigbee.ts:273:26 - error TS2554: Expected 2 arguments, but got 0.

273     return this.herdsman.touchlinkFactoryReset();
                             ~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/zigbee-herdsman/dist/controller/controller.d.ts:48:27
    48     touchlinkFactoryReset(ieeeAddr: string, channel: number): Promise<boolean>;
                                 ~~~~~~~~~~~~~~~~
    An argument for 'ieeeAddr' was not provided.


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by EdwardChamberlain** [comment]
> I found "homebridge-z2m" plugin that would directly connect it to z2m but I don't know yet how stable is it.

I spoke to the developer of that and it currently does not support switches or a "add to zigbee" button.

**Comment by madchicken** [comment]
@EdwardChamberlain I fix the compilation issue. Testing it now on my local raspberry.

**Comment by madchicken** [comment]
@EdwardChamberlain @manuchis I spend a couple of hours trying to understand if zigbee2mqtt has differences with this plugin. I did not find many different things in the code between the two. I fixed a couple in the `v1.0.6` branch, but I doubt they will make differences for your problem. I have the plugin up and running here and I don't see any issue. Did you try the new branch?

**Comment by manuchis** [comment]
It is weird because I still get the network error and I believe I have to pair everything again, however I cannot delete devices from cache. After doing so, I restart the homebridge but they come up again. I understand that the zigbee DB doessn’t exist anymore, right? do I have to do anything else?

```
[11/17/2020, 19:28:05] [ZigBee Hub] Reading 'state' to '0x00124b001f79d7f0' failed: 'Error: Read 0x00124b001f79d7f0/11 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
````

Manuel Portela, PhD
Cel Es. +34 600 851 104
Follow me: @Portela_Man
manuchis.net

**Comment by madchicken** [comment]
The database is stored into the homebridge config folder. To remove old devices you need to delete the db and do a factory reset of them. I would also clear the homebridge accessories cache

**Comment by madchicken** [comment]
Yes, to unlink them you need to factory reset them unfortunately

**Comment by manuchis** [comment]
So if they are linked, I don’t know why I get the network error.

Manuel Portela, PhD
Cel Es. +34 600 851 104
Follow me: @Portela_Man
manuchis.net

**Comment by manuchis** [comment]
Si, I’ve re linked all the devices today and everything is working. Let’s see what happens during this week.

Manuel Portela, PhD
Cel Es. +34 600 851 104
Follow me: @Portela_Man
manuchis.net

**Comment by manuchis** [comment]
Well, after some days running 1.0.6 it seems that everything is stable. I got some warnings and "no response" but the homebridge service doesn't crash.

**Comment by EdwardChamberlain** [comment]
I seem to still be getting the issue with an "unresolved promise" on 1.0.6 sadly.

**Comment by madchicken** [comment]
Please, try 1.0.9

**Comment by madchicken** [comment]
This issue is been (finally) solved in 1.1.0 version (still in unstable state ATM). You can try it by doing

    `npm I homebridge-zigbee-nt@unstable -g`

**Comment by EdwardChamberlain** [comment]
I haven't seen this issue since I have been running on 1.1.0 and in general, the whole system seems more responsive. Looks promising! Will keep an eye on it.

**Comment by madchicken** [comment]
Fixed in v1.1.0

**Comment by EdwardChamberlain** [comment]
Running on 1.1.2 I have picked up a few unresolved promises which could be related to slow performance:

```
Rejecting unresolved promise after 9935ms ("0x000d6ffffeff6164|1")
Rejecting unresolved promise after 9920ms ("0x680ae2fffe7d5012|1")
Rejecting unresolved promise after 9886ms ("0x680ae2fffe770c4f|1")
Rejecting unresolved promise after 9412ms ("0x000d6ffffeff6164|1")
Rejecting unresolved promise after 9409ms ("0x086bd7fffe519524|1")
Rejecting unresolved promise after 9405ms ("0x086bd7fffe3521ed|1")
Rejecting unresolved promise after 9401ms ("0x680ae2fffe7d5012|1")
Rejecting unresolved promise after 9381ms ("0x680ae2fffe770c4f|1")
Rejecting unresolved promise after 6414ms ("0x000d6ffffeff6164|1")
Rejecting unresolved promise after 6408ms ("0x086bd7fffe519524|1")
Rejecting unresolved promise after 6402ms ("0x086bd7fffe3521ed|1")
Rejecting unresolved promise after 6396ms ("0x680ae2fffe7d5012|1")
Rejecting unresolved promise after 6371ms ("0x680ae2fffe770c4f|1")
Rejecting unresolved promise after 5906ms ("0x000d6ffffeff6164|1")
Rejecting unresolved promise after 5901ms ("0x086bd7fffe519524|1")
Rejecting unresolved promise after 5897ms ("0x086bd7fffe3521ed|1")
Rejecting unresolved promise after 5893ms ("0x680ae2fffe7d5012|1")
Rejecting unresolved promise after 5861ms ("0x680ae2fffe770c4f|1”)
```

This is the following log (incase its any use): 
```
[1/6/2021, 19:52:36] [ZigBee] Zigbee message from 0x000d6ffffeff6164 readResponse
[1/6/2021, 19:52:36] [ZigBee] Zigbee message from 0x680ae2fffe770c4f readResponse
[1/6/2021, 19:52:36] [ZigBee] Zigbee message from 0x000d6ffffeff6164 readResponse
[1/6/2021, 19:52:36] [ZigBee] Zigbee message from 0x086bd7fffe519524 readResponse
[1/6/2021, 19:52:36] [ZigBee] Zigbee message from 0x086bd7fffe3521ed readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe7d5012 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe770c4f readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe7d5012 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x000d6ffffeff6164 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x086bd7fffe519524 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x086bd7fffe3521ed readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe7d5012 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe770c4f readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x000d6ffffeff6164 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x086bd7fffe519524 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x086bd7fffe3521ed readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe7d5012 readResponse
[1/6/2021, 19:52:37] [ZigBee] Zigbee message from 0x680ae2fffe770c4f readResponse
[1/6/2021, 19:55:02] [ZigBee] Decoded state from incoming message { occupancy: false }
[1/6/2021, 19:55:02] [ZigBee] Updating state of device TRADFRI motion sensor:  { occupancy: false }
[1/6/2021, 19:57:33] [ZigBee] Zigbee message from 0xec1bbdfffed0a229 commandOn
[1/6/2021, 19:57:33] [ZigBee] Decoded state from incoming message { action: 'on' }
[1/6/2021, 19:57:33] [ZigBee] Updating state of device TRADFRI shortcut button:  { action: 'on' }
[1/6/2021, 19:57:34] [ZigBee] Reading 'state' from '0x680ae2fffe7d5012, message in queue 0x680ae2fffe7d5012|1'
[1/6/2021, 19:57:34] [ZigBee] Sent 1 messages for device TRADFRI control outlet
[1/6/2021, 19:57:34] [ZigBee] Zigbee message from 0x680ae2fffe7d5012 readResponse
```
